--- 
title: "History of English"
author: "Martin Schweinberger"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
  - \usepackage{gb4e} \noautomath
---

# Course information

## Course description

This course addresses how and why languages change and introduces students to the history of the English language. During the sessions, we will discuss different periods of English, their linguistic features as well as the cultural forces that characterize and have shaped them. In addition, this course will familiarize students with basic concepts of historical linguistics, e.g. family trees and reconstruction, and will elaborate on how language is analyzed from a diachronic perspective using hands-on corpus exercises to investigate selected features (diachronic changes of nominal suffixes and the alternation in the 3rd person singular morpheme). Finally, students will learn about different types of changes, i.e. how changes affect distinct levels of the linguistic system (sound change, semantic change, grammaticalization), and their social embedding (historical sociolinguistics).

## Formal requirements
To pass this course, you have to...  
  + be admitted in this(!) course   
  + sign in to „Ang072 History of English Language and
Culture“ on Moodle (password: history);  
  + Do one in-class activity/presentation/task;  
  + sign up for the term paper/final exam;  
  + pass the final exam or hand in your term paper 4 weeks after the final week of teaching.

If you fail to meet any of these requirements, you
cannot pass this course!

## In-Class Activity/Presentation/Task

As an in-class activities or tasks you may choose between...  
  + be moderator for a text  
  + design and do exercises in class (e.g. quiz, work sheet,
group work)  
  + short presentation on additional material  
  + create a presentation on the text for the session (will be uploaded to Moodle but will not be shown in class)  
  + prepare questions about the text for the session that other students will have to answer online before the session

## Session Structure
Each session will follow this (approximate) template:  
  + 5 min recap  
  + 30-45 min chapter moderation  
  + 15-20 min exercises  
  + 15-30 min lecture  
  + 10-15 min presentation


## Coursebook and Pensum

The main coursebook we will be using in class is the following:

- Galloway, Nicola and Rose, Heath. 2015. *Introducing global Englishes*. Routledge.
  
You should purchase this book: it has been ordered at Akademika bookshop.

The other readings below, as well as possible additional material, will be made available electronically on Blackboard throughout the course (either for download or as links to e-readings from the library):

- Altbach, Philip G. (2007). The Imperial Tongue: English as the Dominating Academic Language. *Economic and Political Weekly*, September 8, 2007.

- Dunstan, Stephany B. and Jaeger, Audrey J. (2015). Dialect and influences on the academic experiences of college students. *The Journal of Higher Education* 86(5):776-803.

- Fonyuy, K. E. (2010). The rush for English education in urban Cameroon: Sociolinguistic implications and prospects. *English Today*, 26(1), 34-42.

- Kerswill, Paul (2014). The objectification of ‘Jafaican’: The discoursal embedding of Multicultural London English in the British media. In Androutsopoulos, Jannis (ed.), *The media and sociolinguistic change*, 428-55. Berlin: Walter de Gruyter.

- Momma, Haruko and Matto, Michael. (eds.) 2008. *A companion to the history of the English language*. Malden, MA: Blackwell.

  - Chapter 50: Ziegler, Mary B. Migration and motivation in the development of African American Vernacular English. 509-520.

  - Chapter 54: Mufwene, Salikoko S. Creoles and pidgins. 553-566.

- Rickford, John R. and McWhorter, John. 1998. Language contact and language generation: Pidgins and creoles. In Coulmas, F. (ed) *The Handbook of Sociolinguistics*. Oxford: Blackwell. 238-256.

- **Svartvik, Jan and Leech, Geoffrey. 2016. *English: one tongue, many voices*. Basingstoke: Palgrave Macmillan. Chapters 2 and 3** and pp. 101-118.


## Recommendations
Media  

  + The History of English Podcast (highly recommended): http://historyofenglishpodcast.com/  
  + Documentaries and documentary series (available on www.youtube.com):  
    + The History of the English Language,  
    + A History of Britain,  
    + The Adventure of English,  
    + The Story of English

Literature  

  + Knowles, Gerry. 1997. A Cultural History of the English Language. Arnold: London.  
  + Barber, Charles, Beal, Joan C. & Shaw, Philip A. 2009. The English language: A historical introduction. Cambridge: Cambridge University Press.  
  + Baugh and Cable (1993), Brinton and Arnovick (2006), van Gelderen (2006), Hogg and Denison (2006), (Deutscher 2010), and Crystal (2006).

## Course plan (approximate)

| Session | Topic | 
|-----|-------------------------|
| 1  | Formalities, overview, and teaser |
| 2  |  Introduction |
| 3  |  Origins of English |
| 4  |  History of English |
| 5  |  Old English |
| 6  |  Middle English |
| 7  |  Early and Late Modern English |
| 8  |  Present Day English |
| 9  |  Future of English |
| 10  |  How Structure Arises |
| 11  |  Language Variation and Change |
| 12  |  Empirical approaches in Diachronic Linguistics  |

## Primer: what’s ahead

Have a look at the following word pairs and think about why
they might be different:

1. house : houses
2. mouse : mice

1. Pre-English/Proto-Germanic: Starting Point
   - husa! huso
   - mus! musiz
   
2. Pre-English: I-Mutation, Final Syllables Weakened
   - husa! huso
   - mus! mysi(z)
   
3. Early Old English: Loss of Final Syllables
   - hus! hus
   - mus! mys
   
4. Late Old English: Unrounding of /y/ to /i/
   - hus! hus
   - mus! mis

5. Middle/Early Modern English
   - Great Vowel Shift: Diphthongisation of /u:/ and /i:/ to /@u/ and /@i/; house starts getting an explicit plural
     - h@us ! h@us(en/es)
     - m@us ! m@is
   
6. Modern English
   - Diphthongisation continued to /aU, aI/; alternative plurals of house disappear, leaving just one, regular plural
     - haUs <house> ! haUz@s <houses>
     - maUs <mouse> ! maIs <mice>
